import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="es">
//       <body>
//         <header style={{ padding: '10px', background: '#eee' }}>
//           <h2>Mi app de Next.js</h2>
//         </header>
//         <nav style={{ padding: '10px', background: '#ccc' }}>
//           <Link href="/">Inicio</Link> &nbsp;&nbsp;
//           <Link href="/productos">Productos</Link> &nbsp;&nbsp; 
//           <Link href="/servicios">Servicios</Link>
//         </nav>

//         {children}
        
//         <footer style={{ padding: '10px', background: '#eee' }}>
//           <p>Footer de la aplicación</p>
//         </footer>
//       </body>
//     </html>
//   );
// }


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="min-h-screen flex flex-col bg-gray-100 text-gray-800">

        {/* HEADER */}
        <header className="bg-white shadow-md">
          <div className="max-w-5xl mx-auto px-4 py-4">
            <h2 className="text-2xl font-bold text-blue-600">
              Mi app de Next.js
            </h2>
          </div>
        </header>

        {/* NAV */}
        <nav className="bg-blue-600 text-white">
          <div className="max-w-5xl mx-auto px-4 py-3 flex gap-6">
            <Link href="/" className="hover:underline">
              Inicio
            </Link>
            <Link href="/productos" className="hover:underline">
              Productos
            </Link>
            <Link href="/servicios" className="hover:underline">
              Servicios
            </Link>
          </div>
        </nav>

        {/* MAIN CONTENT */}
        <main className="flex-1 max-w-5xl mx-auto w-full px-4 py-6">
          {children}
        </main>

        {/* FOOTER */}
        <footer className="bg-white border-t">
          <div className="max-w-5xl mx-auto px-4 py-4 text-sm text-gray-500">
            <p>Footer de la aplicación</p>
          </div>
        </footer>

      </body>
    </html>
  );
}