import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <header style={{ padding: '10px', background: '#eee' }}>
          <h2>Mi app de Next.js</h2>
        </header>
        <nav style={{ padding: '10px', background: '#ccc' }}>
          <Link href="/">Inicio</Link> &nbsp;&nbsp;
          <Link href="/productos">Productos</Link> &nbsp;&nbsp; 
          <Link href="/servicios">Servicios</Link>
        </nav>

        {children}
        
        <footer style={{ padding: '10px', background: '#eee' }}>
          <p>Footer de la aplicación</p>
        </footer>
      </body>
    </html>
  );
}
